spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productms
          uri:
            http://localhost:8082/
          predicates:
            - Path=/productApi/**
        - id: ekartms
          uri:
            http://localhost:8080/
          predicates:
            - Path=/kartApi/**
        - id: customerms
          uri:
            http://localhost:8081/
          predicates:
            - Path=/customers/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

server:
  port: 8084

okta:
  oauth2:
    issuer: https://dev-09676956.okta.com/oauth2/default